label: metadata-site
icon: search

columns:
  - width: 7/12
    fields:
      metaHeadline:
        label: global-meta-headline
        type: headline
        numbered: false
        help: global-meta-headline-help
      metaTemplate:
        label: meta-title-template
        type: text
        help: meta-title-template-help
      metaDescription:
        label: meta-description
        type: textarea
        help: meta-description-help
        buttons: false
      seoL:ine1:
        type: line
      ogHeadline:
        label: global-og-headline
        type: headline
        numbered: false
        help: global-og-headline-help
      ogTemplate:
        label: og-title-template
        type: text
        default: '{{ title }}'
        help: meta-title-template-help
        placeholder: '{{ site.metaTemplate }}'
      ogDescription:
        label: og-description
        type: textarea
        buttons: false
        placeholder: '{{ site.metaDescription }}'
      ogSiteName:
        label: og-site-name
        type: text
        default: '{{ site.title }}'
        placeholder: '{{ site.title }}'
        width: 1/2
      ogImage:
        label: og-image
        extends: seo/og-image
        empty: og-image-empty
        width: 1/2
      twitterCardType:
        label: twitter-card-type
        width: 1/2
        type: select
        default: summary
        required: true
        options:
          summary: "{{ t('summary') }}"
          summary_large_image: "{{ t('summary_large_image') }}"
        help: twitter-card-type-help
      seoLine2:
        type: line
      socialMediaAccounts:
        label: social-media-accounts
        type: object
        help: social-media-accounts-help
        fields:
          twitter:
            label: Twitter
            type: url
            icon: twitter
            placeholder: https://twitter.com/my-company
          linkedin:
            label: LinkedIn
            type: url
            icon: linkedin
            placeholder: https://www.linkedin.com/company/my-company
          instagram:
            label: Instagram
            type: url
            icon: instagram
            placeholder: https://instagram.com/my-company
          facebook:
            label: Facebook
            type: url
            icon: facebook
            placeholder: https://www.facebook.com/my-company
          youtube:
            label: YouTube
            type: url
            icon: youtube
            placeholder: https://www.youtube.com/channel/my-company
  - width: 5/12
    sticky: true
    sections:
      seoPreview:
        type: seo-preview
